1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [124]:
a1 = np.zeros(10)
a[4] = 1

4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
np.arange(10, 49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [7]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [8]:
b = ([1,2,0,0,4,0])
np.nonzero(b)

(array([0, 1, 4]),)

7. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 3x3x3 array with random values (★☆☆)

In [14]:
np.random.random((3,3,3))

array([[[0.43014981, 0.73985185, 0.17828396],
        [0.09472042, 0.96884858, 0.23225721],
        [0.0144813 , 0.26645411, 0.86146181]],

       [[0.62305653, 0.71063315, 0.46386607],
        [0.90419519, 0.33662162, 0.96640568],
        [0.29770579, 0.0489828 , 0.42526911]],

       [[0.66360198, 0.3285239 , 0.13008855],
        [0.01065832, 0.32700378, 0.80437327],
        [0.34197618, 0.58154827, 0.33811129]]])

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
c = np.random.random((10,10))
np.min(c), np.max(c)

(1.986223957828326e-05, 0.9947981954357358)

10. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
d= np.random.random(30)
np.mean(d)

0.484106361463312

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [59]:
np.diag([1,2,3,4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

12. Normalize a 5x5 random matrix (★☆☆)

In [69]:
g = np.random.random((5,5))
g1 = (g - np.mean(g))/np.std(g)
print(g)
print(g1)
print(round(np.mean(g1)))
print(np.std(g1))

[[0.58975618 0.17423925 0.27813015 0.2919102  0.452387  ]
 [0.66135699 0.23231568 0.79274393 0.99693886 0.96209863]
 [0.67647848 0.8710082  0.50234865 0.32586319 0.24106791]
 [0.77495991 0.66574027 0.40706528 0.03499388 0.96813499]
 [0.15918123 0.99894523 0.47568599 0.45253714 0.13913206]]
[[ 0.22088352 -1.19646284 -0.84208645 -0.79508208 -0.24768875]
 [ 0.46511699 -0.9983616   0.9132836   1.60980139  1.49095984]
 [ 0.51669708  1.18024641 -0.07726736 -0.67926696 -0.96850737]
 [ 0.85262153  0.48006856 -0.40228309 -1.67143485  1.51155014]
 [-1.2478264   1.61664519 -0.16821487 -0.24717662 -1.31621498]]
0
1.0


13. How to find common values between two arrays? (★☆☆)

In [45]:
x = np.random.randint(1, 10, size=8)
y = np.random.randint(2, 10, size=8)
print(x)
print(y)
np.intersect1d(x,y)

[6 9 3 8 7 5 9 4]
[6 3 6 8 4 5 6 5]


array([3, 4, 5, 6, 8])

14. Create a random vector of size 10 and sort it (★★☆)

In [47]:
vector = np.random.random(10)
print(vector)
np.sort(vector)

[0.46465485 0.75806492 0.72523456 0.97640692 0.36120642 0.70512692
 0.03929192 0.19324478 0.65761867 0.72581255]


array([0.03929192, 0.19324478, 0.36120642, 0.46465485, 0.65761867,
       0.70512692, 0.72523456, 0.72581255, 0.75806492, 0.97640692])

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [77]:
vec = np.random.random(10)
vec[np.argmax(vec)] = 0
print(vec)


[0.73420402 0.85780177 0.76605636 0.6143478  0.         0.82580202
 0.17161049 0.63709603 0.24147078 0.45329615]


16. Subtract the mean of each row of a matrix (★★☆)

In [114]:
matrix = np.random.random((3,3))
print(np.mean(matrix))
print(matrix)
y= matrix-np.mean(matrix,axis=1,keepdims=True)
print(y)

0.5712116560180656
[[0.20954354 0.46113399 0.80249361]
 [0.68161104 0.89800929 0.72956455]
 [0.22293132 0.13930964 0.99630794]]
[[-0.28151351 -0.02992305  0.31143656]
 [-0.08811726  0.128281   -0.04016374]
 [-0.22991832 -0.31353999  0.54345831]]


17. How to get the n largest values of an array (★★★)

In [115]:
Z = np.arange(10000) 
print(Z)
np.random.shuffle(Z)
print(Z)
Z[np.argpartition(Z, -5)[-5:]]



[   0    1    2 ... 9997 9998 9999]
[4429 2100 7877 ... 6819 6012 2521]


array([9995, 9996, 9997, 9999, 9998])

In [107]:
Z[np.argsort(Z)[-5:]]


array([9995, 9996, 9997, 9998, 9999])

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

In [123]:
x = np.random.randint(0, 10, (5, 3))
print(x)
np.where(x > 4, x**2, x)

[[9 7 2]
 [6 8 2]
 [6 7 8]
 [0 7 5]
 [2 4 1]]


array([[81, 49,  2],
       [36, 64,  2],
       [36, 49, 64],
       [ 0, 49, 25],
       [ 2,  4,  1]])